/** (c) 2013, Arizona Board of Regents for and on behalf of Arizona State University.
 * This file is part of LAITS.
 *
 * LAITS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LAITS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public License
 * along with LAITS.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.asu.laits.gui;

import edu.asu.laits.editor.ApplicationContext;
import edu.asu.laits.properties.GlobalProperties;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;

import org.apache.log4j.Logger;

/**
 *
 * @author ramayantiwari
 */
public class UserRegistration extends javax.swing.JDialog {

    /**
     * Logger
     */
    private static Logger devLogs = Logger.getLogger("DevLogs");
    private static Logger activityLogs = Logger.getLogger("ActivityLogs");

    /**
     * Creates new form UserRegistration2
     */
    public UserRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        setLocationRelativeTo(null);
        hideErrorMessages();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstnameInputBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        firstnameErrMsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelAppMode = new javax.swing.JLabel();
        asuidInputBox = new javax.swing.JTextField();
        lastnameInputBox = new javax.swing.JTextField();
        lastnameErrMsg = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        asuidErrMsg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioButtonStudent = new javax.swing.JRadioButton();
        radioButtonAuthor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LAITS User Registration");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(firstnameInputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 61, 158, -1));

        jLabel1.setText("First Name*: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 67, 90, -1));

        firstnameErrMsg.setForeground(new java.awt.Color(250, 0, 0));
        firstnameErrMsg.setText("jLabel5");
        getContentPane().add(firstnameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 89, -1));

        jLabel2.setText("Last Name*: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 113, 80, -1));

        labelAppMode.setText("Mode*:");
        labelAppMode.setPreferredSize(new java.awt.Dimension(57, 16));
        getContentPane().add(labelAppMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 200, 90, -1));
        getContentPane().add(asuidInputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 153, 158, -1));
        getContentPane().add(lastnameInputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 107, 158, -1));

        lastnameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        lastnameErrMsg.setText("jLabel5");
        getContentPane().add(lastnameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 89, -1));

        spacer.setForeground(new java.awt.Color(252, 0, 0));
        spacer.setText("      ");
        getContentPane().add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 256, 89, 20));

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("User Registration");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 0, 169, 37));

        asuidErrMsg.setForeground(new java.awt.Color(252, 0, 0));
        asuidErrMsg.setText("jLabel5");
        getContentPane().add(asuidErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 89, -1));

        jLabel5.setText("ASU ID*: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 159, 80, -1));

        buttonGroup1.add(radioButtonStudent);
        radioButtonStudent.setSelected(true);
        radioButtonStudent.setText("Student");
        getContentPane().add(radioButtonStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        buttonGroup1.add(radioButtonAuthor);
        radioButtonAuthor.setText("Author");
        getContentPane().add(radioButtonAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
      // TODO add your handling code here:
      hideErrorMessages();

      String firstName = firstnameInputBox.getText();
      String lastName = lastnameInputBox.getText();
      String asuId = asuidInputBox.getText();
      String appMode = null;
      if (radioButtonStudent.isSelected()) {
          appMode = "STUDENT";
      } else {
          appMode = "AUTHOR";
      }

      devLogs.debug("User Registration Input: " + firstName + " " + lastName + " " + asuId + " " + appMode);
      
      
      if (validateInputFields(firstName, lastName, asuId)) {
          logs.debug("User Registration Successful");
          activityLogs.debug("User registered with "+firstName+" "+lastName+" "+asuId);
          
          ApplicationContext.setUserID(asuId);
          ApplicationContext.setAppMode(appMode);

          // Update this User record in database
          final String WEB = "http://laits.engineering.asu.edu/updateprob.php";

          try {
              ApplicationContext.setUserValid(true);
              this.dispose();

              // Open Main Window
              try {
                  String uiClassName = GlobalProperties.getInstance().getUITheme();
                  if (null != uiClassName) {
                      try {
                          UIManager.setLookAndFeel((LookAndFeel) Class.forName(
                                  uiClassName).newInstance());
                      } catch (Exception e) {
                          System.err.println("Could not load theme: " + uiClassName);
                      }
                  }

                  // Main application window of LAITS
                  MainWindow window = new MainWindow();

                  window.setVisible(true);

              } catch (Exception e) {
                  JOptionPane.showMessageDialog(null, e.getMessage(),
                          "An error has occured", JOptionPane.ERROR_MESSAGE);

                  e.printStackTrace();
              }


          } catch (Exception e) {
              devLogs.trace("Error in Updating student completed prob. " + e.getMessage());
          }


      }
  }//GEN-LAST:event_buttonSubmitActionPerformed

  private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
      // TODO add your handling code here:
      this.dispose();
  }//GEN-LAST:event_buttonCancelActionPerformed

    private boolean validateInputFields(String fName, String lName, String id) {
        boolean formHasErr = false;

        if (fName == null || fName.isEmpty()) {
            firstnameErrMsg.setText(" Required ");
            firstnameErrMsg.setVisible(true);
            formHasErr = true;
        }

        if (lName == null || lName.isEmpty()) {
            lastnameErrMsg.setText(" Required ");
            lastnameErrMsg.setVisible(true);
            formHasErr = true;
        }

        if (id == null || id.isEmpty()) {
            asuidErrMsg.setText(" Required ");
            asuidErrMsg.setVisible(true);
            formHasErr = true;
        } else {
            if (id.length() != 10 || !isInteger(id)) {
                asuidErrMsg.setText(" Invalid ");
                asuidErrMsg.setVisible(true);
                formHasErr = true;
            }
        }

        return !formHasErr;
    }

    private void hideErrorMessages() {
        firstnameErrMsg.setVisible(false);
        lastnameErrMsg.setVisible(false);
        asuidErrMsg.setVisible(false);
    }

    /**
     * Method to test if String contains only Integers
     *
     * @param input: String to test
     * @return
     */
    private boolean isInteger(String input) {
        try {
            Integer.parseInt(input);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asuidErrMsg;
    private javax.swing.JTextField asuidInputBox;
    private javax.swing.JButton buttonCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel firstnameErrMsg;
    private javax.swing.JTextField firstnameInputBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelAppMode;
    private javax.swing.JLabel lastnameErrMsg;
    private javax.swing.JTextField lastnameInputBox;
    private javax.swing.JRadioButton radioButtonAuthor;
    private javax.swing.JRadioButton radioButtonStudent;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables
    /**
     * Logger *
     */
    private static Logger logs = Logger.getLogger(UserRegistration.class);
}
