/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphRangeEditor.java
 *
 * Created on Oct 23, 2011, 5:52:48 PM
 */
package edu.asu.laits.editor;

import edu.asu.laits.gui.MainWindow;
import edu.asu.laits.model.Task;
import edu.asu.laits.model.Vertex;
import edu.asu.laits.model.Graph;
import edu.asu.laits.model.Times;
import java.awt.Color;
import java.util.Iterator;
import org.apache.log4j.Logger;

/**
 *
 * @author Ram
 */
public class GraphRangeEditor extends javax.swing.JDialog {

    GraphEditorPane editorPane;
    Graph graph;
    private static Logger logs = Logger.getLogger("DevLogs");
    
    /** Creates new form GraphRangeEditor */
    public GraphRangeEditor(GraphEditorPane editorPane, boolean modal) {
        super(MainWindow.getInstance(), modal);
        this.editorPane = editorPane;
        this.graph = editorPane.getModelGraph();
        initComponents();
        labelErrorTimeStep.setVisible(false);
        labelErrorInitial.setVisible(false);
        labelErrorFinal.setVisible(false);
        try{
            logs.debug("Initializing Range Editor "+ "Unit time : " + ApplicationContext.getCurrentTask().getChartUnits());
            textIntialValue.setText(String.valueOf(ApplicationContext.getCurrentTask().getTimes().getStartTime()));
            textFinalValue.setText(String.valueOf(ApplicationContext.getCurrentTask().getTimes().getEndTime()));
            textTimeStep.setText(String.valueOf(ApplicationContext.getCurrentTask().getTimes().getTimeStep()));
            comboUnits.setSelectedItem(ApplicationContext.getCurrentTask().getChartUnits());

        }catch(Exception e){
            e.printStackTrace();
        }
        this.setBounds((this.getToolkit().getScreenSize().width)/2 - 150, (this.getToolkit().getScreenSize().height)/2 - 125, 300,250);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIntialValue = new javax.swing.JLabel();
        labelFinalValue = new javax.swing.JLabel();
        labelUnits = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        textIntialValue = new javax.swing.JTextField();
        textFinalValue = new javax.swing.JTextField();
        comboUnits = new javax.swing.JComboBox();
        graphPanelHeading = new javax.swing.JLabel();
        labelErrorInitial = new javax.swing.JLabel();
        labelErrorTimeStep = new javax.swing.JLabel();
        labelFinalValue1 = new javax.swing.JLabel();
        textTimeStep = new javax.swing.JTextField();
        labelErrorFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Graph Range Editor");
        setBounds(new java.awt.Rectangle(300, 200, 100, 150));
        setModal(true);
        setName("GraphModelEditor"); // NOI18N
        setResizable(false);

        labelIntialValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelIntialValue.setText("Initial Value");
        labelIntialValue.setFocusable(false);

        labelFinalValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelFinalValue.setText("Final Value");
        labelFinalValue.setFocusable(false);

        labelUnits.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelUnits.setText("Units");
        labelUnits.setFocusable(false);

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        textIntialValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textIntialValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textIntialValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textIntialValueFocusLost(evt);
            }
        });

        textFinalValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFinalValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFinalValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFinalValueFocusLost(evt);
            }
        });

        comboUnits.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Years", "Months", "Days", "Hours", "Mins" }));
        comboUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUnitsActionPerformed(evt);
            }
        });

        graphPanelHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        graphPanelHeading.setText("Edit Graph Settings");

        labelErrorInitial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelErrorInitial.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorInitial.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelErrorInitial.setText("Intial Value can not be empty !");
        labelErrorInitial.setFocusable(false);

        labelErrorTimeStep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelErrorTimeStep.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorTimeStep.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelErrorTimeStep.setText("Time Step can not be empty !");
        labelErrorTimeStep.setFocusable(false);

        labelFinalValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelFinalValue1.setText("Time Step");
        labelFinalValue1.setFocusable(false);

        textTimeStep.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTimeStep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textTimeStepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textTimeStepFocusLost(evt);
            }
        });

        labelErrorFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelErrorFinal.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorFinal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelErrorFinal.setText("Final Value can not be empty !");
        labelErrorFinal.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(graphPanelHeading)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(buttonSave))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFinalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIntialValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(labelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textIntialValue)
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFinalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(buttonCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(labelFinalValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(textTimeStep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(50, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelErrorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelErrorInitial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelErrorTimeStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graphPanelHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIntialValue)
                    .addComponent(textIntialValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorInitial)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFinalValue)
                    .addComponent(textFinalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFinalValue1)
                    .addComponent(textTimeStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorTimeStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnits))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // Validating user input
        boolean isInputValid = true;
        labelErrorInitial.setVisible(false);
        labelErrorTimeStep.setVisible(false);
        if(textIntialValue.getText().isEmpty()){
            labelErrorInitial.setVisible(true);
            textIntialValue.requestFocus();
            isInputValid = false;
        }
        if(textFinalValue.getText().isEmpty()){
            labelErrorTimeStep.setVisible(true);
            textFinalValue.requestFocus();
            isInputValid = false;
        }
        if(textTimeStep.getText().isEmpty()){
            labelErrorTimeStep.setVisible(true);
            textTimeStep.requestFocus();
            isInputValid = false;
        }
        if(isInputValid){
            // Saving User's input in the Server Task object
            double startTime = Double.parseDouble(textIntialValue.getText());
            double endTime = Double.parseDouble(textFinalValue.getText());
            double timeStep = Double.parseDouble(textTimeStep.getText());

            //Checking if end time is less than start time
            if((endTime-startTime)*timeStep<0){
                labelErrorTimeStep.setText("End Time can not be less than Start Time");
                labelErrorTimeStep.setVisible(true);
                textFinalValue.requestFocus();
                return;
            }

            String units = String.valueOf(comboUnits.getSelectedItem());
            try{
                ApplicationContext.getCurrentTask().setTimes(new Times(startTime,endTime,timeStep));
                ApplicationContext.getCurrentTask().setChartUnits(units);
                
                Iterator<Vertex> vertices = editorPane.getModelGraph().vertexSet().iterator();
                while(vertices.hasNext()){
                    vertices.next().setGraphsStatus(Vertex.GraphsStatus.UNDEFINED);
                }
                editorPane.repaint();
            
            }catch(Exception e){
                e.printStackTrace();
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // Closing the window on Cancel
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textIntialValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIntialValueFocusGained
        textIntialValue.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_textIntialValueFocusGained

    private void textFinalValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFinalValueFocusGained
        textFinalValue.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_textFinalValueFocusGained

    private void textIntialValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIntialValueFocusLost
        textIntialValue.setBackground(Color.white);
    }//GEN-LAST:event_textIntialValueFocusLost

    private void textFinalValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFinalValueFocusLost
        textFinalValue.setBackground(Color.white);
    }//GEN-LAST:event_textFinalValueFocusLost

    private void comboUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUnitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUnitsActionPerformed

    private void textTimeStepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTimeStepFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textTimeStepFocusGained

    private void textTimeStepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTimeStepFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textTimeStepFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox comboUnits;
    private javax.swing.JLabel graphPanelHeading;
    private javax.swing.JLabel labelErrorFinal;
    private javax.swing.JLabel labelErrorInitial;
    private javax.swing.JLabel labelErrorTimeStep;
    private javax.swing.JLabel labelFinalValue;
    private javax.swing.JLabel labelFinalValue1;
    private javax.swing.JLabel labelIntialValue;
    private javax.swing.JLabel labelUnits;
    private javax.swing.JTextField textFinalValue;
    private javax.swing.JTextField textIntialValue;
    private javax.swing.JTextField textTimeStep;
    // End of variables declaration//GEN-END:variables
}
