/*
 * LAITS Project
 * Arizona State University
 * 
 * @author: rptiwari
 */

package edu.asu.laits.gui.nodeeditor;


import java.awt.*;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Megana
 */
public class GraphsPanelView extends javax.swing.JPanel {

  JPanel grafica;

  //the width and height of the panel
  int width, height;
  private NodeEditor nodeEditor;
  
  private static GraphsPanelView graphView;
  
  /** Logger **/
  private static Logger logs = Logger.getLogger(GraphsPanelView.class);
  

  public GraphsPanelView(NodeEditor ne){
    initComponents();
    nodeEditor = ne;
  }
  
  
  public void initPanel(){
    
  }
  
  
  public void testResetLayout() {
    

  }

  /**
   * This method is used when the user selects a name and description for the node
   * currently being edited
   */
  public void updateDescription() {
    descriptionLabel.setText("<html><b>Description:</b> <br/>"  + "</html>");
  }

  public void resetLayout() {
    this.removeAll();
    userAnswerPanel.setPreferredSize(new java.awt.Dimension(300, 200));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);


  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nodeDescriptionLabel = new javax.swing.JLabel();
    allGraphsPanel = new javax.swing.JPanel();
    userGraphLabel = new javax.swing.JLabel();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
    userAnswerPanel = new javax.swing.JPanel();
    correctGraphLabel1 = new javax.swing.JLabel();
    correctGraphLabel2 = new javax.swing.JLabel();
    descriptionLabel = new javax.swing.JLabel();

    nodeDescriptionLabel.setText("<html></html>");

    allGraphsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    userGraphLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    userGraphLabel.setText("Author's Graph:");
    allGraphsPanel.add(userGraphLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
    allGraphsPanel.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, 447, 41));

    userAnswerPanel.setMaximumSize(new java.awt.Dimension(286, 99));
    userAnswerPanel.setPreferredSize(new java.awt.Dimension(286, 99));

    javax.swing.GroupLayout userAnswerPanelLayout = new javax.swing.GroupLayout(userAnswerPanel);
    userAnswerPanel.setLayout(userAnswerPanelLayout);
    userAnswerPanelLayout.setHorizontalGroup(
      userAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 440, Short.MAX_VALUE)
    );
    userAnswerPanelLayout.setVerticalGroup(
      userAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 216, Short.MAX_VALUE)
    );

    allGraphsPanel.add(userAnswerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 216));

    correctGraphLabel1.setText("     ");
    allGraphsPanel.add(correctGraphLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, -1, -1));

    correctGraphLabel2.setText("                   ");
    allGraphsPanel.add(correctGraphLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 369, -1, -1));

    descriptionLabel.setText("<html><b>Description:</b></html>");
    descriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(allGraphsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(287, 287, 287)
            .addComponent(nodeDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(allGraphsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(nodeDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(376, 376, 376))
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel allGraphsPanel;
  private javax.swing.JLabel correctGraphLabel1;
  private javax.swing.JLabel correctGraphLabel2;
  private javax.swing.JLabel descriptionLabel;
  private javax.swing.Box.Filler filler1;
  private javax.swing.JLabel nodeDescriptionLabel;
  private javax.swing.JPanel userAnswerPanel;
  private javax.swing.JLabel userGraphLabel;
  // End of variables declaration//GEN-END:variables

   
}
