/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.asu.laits.gui.nodeeditor;

import edu.asu.laits.editor.ApplicationContext;
import edu.asu.laits.gui.BlockingToolTip;
import edu.asu.laits.model.HelpBubble;
import edu.asu.laits.model.TaskSolution;
import edu.asu.laits.model.Vertex;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.AbstractCellEditor;
import javax.swing.BorderFactory;

import javax.swing.ButtonGroup;
import javax.swing.CellRendererPane;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import org.apache.log4j.Logger;
import edu.asu.laits.model.Vertex.VertexType;

/**
 *
 * @author rjoiner1
 */
public class PlanPanelView2 extends javax.swing.JPanel {

    private String selectedPlan;
    private boolean isViewEnabled = false;
    private NodeEditor nodeEditor;
    
    private static Logger logs = Logger.getLogger("DevLogs");
    private static Logger activityLogs = Logger.getLogger("ActivityLogs");
    private JScrollPane scroll;
    
    public PlanPanelView2(NodeEditor ne) {
        super(new BorderLayout(0, 5));

        nodeEditor = ne;
        initPanel();
    }
    
    public void initPanel() {
        logs.debug("Initializing Plan Panel");

        setSelectedPlan(nodeEditor.getCurrentVertex().getVertexType());
        Vertex currentVertex = this.nodeEditor.getCurrentVertex();
        this.descLabel.setText(currentVertex.getName() + "is a ...");
    }
        
    private void setSelectedPlan(Vertex.VertexType plan){
        if(plan.equals(Vertex.VertexType.CONSTANT)){
            parameterButton.setSelected(true);
        } else if(plan.equals(Vertex.VertexType.STOCK)) {
            accumulatorButton.setSelected(true);
        } else if(plan.equals(Vertex.VertexType.FLOW)) {
            functionButton.setSelected(true);
        }
    }
    
    public Vertex.VertexType getSelectedPlan() {
        if(parameterButton.isSelected()){
            return Vertex.VertexType.CONSTANT;
        } else if(accumulatorButton.isSelected()){
            return Vertex.VertexType.STOCK;
        } else if(functionButton.isSelected()){
            return Vertex.VertexType.FLOW;
        } else {
            return Vertex.VertexType.DEFAULT;
        }
    }
    
    public boolean isViewEnabled() {
        if (nodeEditor.getCurrentVertex().getDescriptionStatus().equals(Vertex.DescriptionStatus.CORRECT)
                || nodeEditor.getCurrentVertex().getDescriptionStatus().equals(Vertex.DescriptionStatus.GAVEUP)) {
            return true;
        } else {
            return false;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        parameterButton = new javax.swing.JRadioButton();
        accumulatorButton = new javax.swing.JRadioButton();
        functionButton = new javax.swing.JRadioButton();
        descLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(590, 473));
        setPreferredSize(new java.awt.Dimension(590, 502));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(parameterButton);
        parameterButton.setText("Parameter");

        buttonGroup1.add(accumulatorButton);
        accumulatorButton.setText("Accumulator");

        buttonGroup1.add(functionButton);
        functionButton.setText("Function");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(accumulatorButton)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, functionButton)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, parameterButton))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(parameterButton)
                .add(98, 98, 98)
                .add(accumulatorButton)
                .add(94, 94, 94)
                .add(functionButton)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        descLabel.setText("This node is a...");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(descLabel)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(descLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accumulatorButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel descLabel;
    private javax.swing.JRadioButton functionButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton parameterButton;
    // End of variables declaration//GEN-END:variables
}
